WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=autovector.xo 
LIB_OBJ?=
#../zmalloc/zmalloc.o
TEST_MAIN?=autovector_test

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk