WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=status.xo
LIB_OBJ?=
#../zmalloc/zmalloc.o
TEST_MAIN?=status_test
BUILD_INCLUDE=status.h
LIB_MODULES?=slice 

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk


