WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=
LIB_OBJ?=../arena/arena.xo
#../zmalloc/zmalloc.o
TEST_MAIN?=skiplist_test

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/arena/lib.mk


